### ISSUE TITLE
cJSON_Parse return null

### ISSUE THREAD

**Issue by muhanGit** [zkemble/MailboxNotifier#1]
Excellent work. Thank you! I wanted to know how you solved cJSON_Parse. It always returns NULL, I can't figure out what the problem is. Can you help please. Part code:
char msg_json[] = "{ \"state\":{ \"desired\":{ \"NumValue\": 3 } }}";
cJSON_Hooks memoryHook;
memoryHook.malloc_fn = OS_Malloc;
memoryHook.free_fn = OS_Free;
cJSON_InitHooks(&memoryHook);

cJSON *json_processing = cJSON_Parse(msg_json);
if(json_processing != NULL)
{
    cJSON *state = cJSON_GetObjectItem(json_processing, "state");
    cJSON *desired = cJSON_GetObjectItem(state, "desired");
    if(desired != NULL)
    {
      .......................
    }
}
else
{
    Trace(1,"Error parse json");
}
cJSON_Delete(json_processing);

The rest all works well: cJSON_CreateObject(), cJSON_AddStringToObject(), cJSON_AddItemToObject();
the only problem is parse

**Comment by ZakKemble** [comment]
But this project doesn't use cJSON_Parse() 😕

Closing since the same issue has been opened in a better place - https://github.com/DaveGamble/cJSON/issues/541
